@hostname=http://localhost
@port=3000
@pathname=api/v1
###
GET {{hostname}}:{{port}}/{{pathname}} HTTP/1.1
###
POST {{hostname}}:{{port}}/{{pathname}}/register HTTP/1.1
Content-Type: application/json

{
    "fullname": "Muhammad Sohail",
    "email": "sohailbalti000@gmail.com",
    "password": "#IrfanBalti1280"
}
